version: 1

ruleSets:
  - path: "."
    override: false

    rules:
      - predefined:
          type: blockExtensions
          extensions: [exe, dll, bat, ps1]
          onMatch: [flag, quarantine]

      - custom:
          condition:
            and:
              - extension:
                  values: [jpg, jpeg]
              - not:
                  fileSignature:
                    values: [JPEG]

          onMatch: [flag, quarantine]

      - predefined:
          type: maxFileSize
          max: 10MiB
          onMatch: flag