version: 1

runtime:
  debounce: 150ms
  workerThreads: 4

statusApi:
  enabled: true
  host: "127.0.0.1"
  port: 8080

mirrors:
  - id: backup
    path: backup
    mode: sourceToMirror
    transferMode: copy
    conflictPolicy: fail
    debounce: 150ms
    maxTransferAttempts: 3
    persistentState: false

ruleSets:
  - path: "."
    override: false

    rules:
      - predefined:
          type: blockExtensions
          extensions: [exe, dll, bat, ps1]
          onMatch: [flag, quarantine]

      - custom:
          condition:
            and:
              - extension:
                  values: [jpg, jpeg]
              - not:
                  fileSignature:
                    values: [JPEG]
          onMatch: [flag, quarantine]

      - predefined:
          type: maxFileSize
          max: 10MiB
          onMatch: flag

      - custom:
          condition:
            extension:
              values: [txt]
          onMatch:
            - allowMirror: backup
